### ISSUE TITLE
not building on xcode.

### ISSUE THREAD

**Issue by MKQasim** [Scandit/datacapture-ios-samples#1]

**Comment by ScanditSupport** [comment]
HI @MKQasim 

this issue might be specific to the setup you use or related to some particular dependency issue. 

Can you please reach out to us directly and share more information around your setup and steps you followed?

[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by MKQasim** [comment]
I replied please check email thanks for positive response.
